// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/PerfilievAlexandr/chat-server/internal/service.HistoryService -o history_service_minimock.go -n HistoryServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/PerfilievAlexandr/chat-server/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// HistoryServiceMock implements service.HistoryService
type HistoryServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSaveHistory          func(ctx context.Context, message domain.Message) (err error)
	inspectFuncSaveHistory   func(ctx context.Context, message domain.Message)
	afterSaveHistoryCounter  uint64
	beforeSaveHistoryCounter uint64
	SaveHistoryMock          mHistoryServiceMockSaveHistory
}

// NewHistoryServiceMock returns a mock for service.HistoryService
func NewHistoryServiceMock(t minimock.Tester) *HistoryServiceMock {
	m := &HistoryServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveHistoryMock = mHistoryServiceMockSaveHistory{mock: m}
	m.SaveHistoryMock.callArgs = []*HistoryServiceMockSaveHistoryParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mHistoryServiceMockSaveHistory struct {
	mock               *HistoryServiceMock
	defaultExpectation *HistoryServiceMockSaveHistoryExpectation
	expectations       []*HistoryServiceMockSaveHistoryExpectation

	callArgs []*HistoryServiceMockSaveHistoryParams
	mutex    sync.RWMutex
}

// HistoryServiceMockSaveHistoryExpectation specifies expectation struct of the HistoryService.SaveHistory
type HistoryServiceMockSaveHistoryExpectation struct {
	mock    *HistoryServiceMock
	params  *HistoryServiceMockSaveHistoryParams
	results *HistoryServiceMockSaveHistoryResults
	Counter uint64
}

// HistoryServiceMockSaveHistoryParams contains parameters of the HistoryService.SaveHistory
type HistoryServiceMockSaveHistoryParams struct {
	ctx     context.Context
	message domain.Message
}

// HistoryServiceMockSaveHistoryResults contains results of the HistoryService.SaveHistory
type HistoryServiceMockSaveHistoryResults struct {
	err error
}

// Expect sets up expected params for HistoryService.SaveHistory
func (mmSaveHistory *mHistoryServiceMockSaveHistory) Expect(ctx context.Context, message domain.Message) *mHistoryServiceMockSaveHistory {
	if mmSaveHistory.mock.funcSaveHistory != nil {
		mmSaveHistory.mock.t.Fatalf("HistoryServiceMock.SaveHistory mock is already set by Set")
	}

	if mmSaveHistory.defaultExpectation == nil {
		mmSaveHistory.defaultExpectation = &HistoryServiceMockSaveHistoryExpectation{}
	}

	mmSaveHistory.defaultExpectation.params = &HistoryServiceMockSaveHistoryParams{ctx, message}
	for _, e := range mmSaveHistory.expectations {
		if minimock.Equal(e.params, mmSaveHistory.defaultExpectation.params) {
			mmSaveHistory.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveHistory.defaultExpectation.params)
		}
	}

	return mmSaveHistory
}

// Inspect accepts an inspector function that has same arguments as the HistoryService.SaveHistory
func (mmSaveHistory *mHistoryServiceMockSaveHistory) Inspect(f func(ctx context.Context, message domain.Message)) *mHistoryServiceMockSaveHistory {
	if mmSaveHistory.mock.inspectFuncSaveHistory != nil {
		mmSaveHistory.mock.t.Fatalf("Inspect function is already set for HistoryServiceMock.SaveHistory")
	}

	mmSaveHistory.mock.inspectFuncSaveHistory = f

	return mmSaveHistory
}

// Return sets up results that will be returned by HistoryService.SaveHistory
func (mmSaveHistory *mHistoryServiceMockSaveHistory) Return(err error) *HistoryServiceMock {
	if mmSaveHistory.mock.funcSaveHistory != nil {
		mmSaveHistory.mock.t.Fatalf("HistoryServiceMock.SaveHistory mock is already set by Set")
	}

	if mmSaveHistory.defaultExpectation == nil {
		mmSaveHistory.defaultExpectation = &HistoryServiceMockSaveHistoryExpectation{mock: mmSaveHistory.mock}
	}
	mmSaveHistory.defaultExpectation.results = &HistoryServiceMockSaveHistoryResults{err}
	return mmSaveHistory.mock
}

// Set uses given function f to mock the HistoryService.SaveHistory method
func (mmSaveHistory *mHistoryServiceMockSaveHistory) Set(f func(ctx context.Context, message domain.Message) (err error)) *HistoryServiceMock {
	if mmSaveHistory.defaultExpectation != nil {
		mmSaveHistory.mock.t.Fatalf("Default expectation is already set for the HistoryService.SaveHistory method")
	}

	if len(mmSaveHistory.expectations) > 0 {
		mmSaveHistory.mock.t.Fatalf("Some expectations are already set for the HistoryService.SaveHistory method")
	}

	mmSaveHistory.mock.funcSaveHistory = f
	return mmSaveHistory.mock
}

// When sets expectation for the HistoryService.SaveHistory which will trigger the result defined by the following
// Then helper
func (mmSaveHistory *mHistoryServiceMockSaveHistory) When(ctx context.Context, message domain.Message) *HistoryServiceMockSaveHistoryExpectation {
	if mmSaveHistory.mock.funcSaveHistory != nil {
		mmSaveHistory.mock.t.Fatalf("HistoryServiceMock.SaveHistory mock is already set by Set")
	}

	expectation := &HistoryServiceMockSaveHistoryExpectation{
		mock:   mmSaveHistory.mock,
		params: &HistoryServiceMockSaveHistoryParams{ctx, message},
	}
	mmSaveHistory.expectations = append(mmSaveHistory.expectations, expectation)
	return expectation
}

// Then sets up HistoryService.SaveHistory return parameters for the expectation previously defined by the When method
func (e *HistoryServiceMockSaveHistoryExpectation) Then(err error) *HistoryServiceMock {
	e.results = &HistoryServiceMockSaveHistoryResults{err}
	return e.mock
}

// SaveHistory implements service.HistoryService
func (mmSaveHistory *HistoryServiceMock) SaveHistory(ctx context.Context, message domain.Message) (err error) {
	mm_atomic.AddUint64(&mmSaveHistory.beforeSaveHistoryCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveHistory.afterSaveHistoryCounter, 1)

	if mmSaveHistory.inspectFuncSaveHistory != nil {
		mmSaveHistory.inspectFuncSaveHistory(ctx, message)
	}

	mm_params := HistoryServiceMockSaveHistoryParams{ctx, message}

	// Record call args
	mmSaveHistory.SaveHistoryMock.mutex.Lock()
	mmSaveHistory.SaveHistoryMock.callArgs = append(mmSaveHistory.SaveHistoryMock.callArgs, &mm_params)
	mmSaveHistory.SaveHistoryMock.mutex.Unlock()

	for _, e := range mmSaveHistory.SaveHistoryMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveHistory.SaveHistoryMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveHistory.SaveHistoryMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveHistory.SaveHistoryMock.defaultExpectation.params
		mm_got := HistoryServiceMockSaveHistoryParams{ctx, message}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveHistory.t.Errorf("HistoryServiceMock.SaveHistory got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveHistory.SaveHistoryMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveHistory.t.Fatal("No results are set for the HistoryServiceMock.SaveHistory")
		}
		return (*mm_results).err
	}
	if mmSaveHistory.funcSaveHistory != nil {
		return mmSaveHistory.funcSaveHistory(ctx, message)
	}
	mmSaveHistory.t.Fatalf("Unexpected call to HistoryServiceMock.SaveHistory. %v %v", ctx, message)
	return
}

// SaveHistoryAfterCounter returns a count of finished HistoryServiceMock.SaveHistory invocations
func (mmSaveHistory *HistoryServiceMock) SaveHistoryAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveHistory.afterSaveHistoryCounter)
}

// SaveHistoryBeforeCounter returns a count of HistoryServiceMock.SaveHistory invocations
func (mmSaveHistory *HistoryServiceMock) SaveHistoryBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveHistory.beforeSaveHistoryCounter)
}

// Calls returns a list of arguments used in each call to HistoryServiceMock.SaveHistory.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveHistory *mHistoryServiceMockSaveHistory) Calls() []*HistoryServiceMockSaveHistoryParams {
	mmSaveHistory.mutex.RLock()

	argCopy := make([]*HistoryServiceMockSaveHistoryParams, len(mmSaveHistory.callArgs))
	copy(argCopy, mmSaveHistory.callArgs)

	mmSaveHistory.mutex.RUnlock()

	return argCopy
}

// MinimockSaveHistoryDone returns true if the count of the SaveHistory invocations corresponds
// the number of defined expectations
func (m *HistoryServiceMock) MinimockSaveHistoryDone() bool {
	for _, e := range m.SaveHistoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveHistoryMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveHistoryCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveHistory != nil && mm_atomic.LoadUint64(&m.afterSaveHistoryCounter) < 1 {
		return false
	}
	return true
}

// MinimockSaveHistoryInspect logs each unmet expectation
func (m *HistoryServiceMock) MinimockSaveHistoryInspect() {
	for _, e := range m.SaveHistoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to HistoryServiceMock.SaveHistory with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SaveHistoryMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSaveHistoryCounter) < 1 {
		if m.SaveHistoryMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to HistoryServiceMock.SaveHistory")
		} else {
			m.t.Errorf("Expected call to HistoryServiceMock.SaveHistory with params: %#v", *m.SaveHistoryMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveHistory != nil && mm_atomic.LoadUint64(&m.afterSaveHistoryCounter) < 1 {
		m.t.Error("Expected call to HistoryServiceMock.SaveHistory")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *HistoryServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveHistoryInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *HistoryServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *HistoryServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveHistoryDone()
}
